/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logb.h"
#include <stdio.h>

void
logb_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	arguments  logb_1_arg;

	float* vector;
	vector[0]=2.5433;
	vector[1]=23.6758;
	vector[2]=5.6578;
	vector[3]=3214.32;
	vector[4]=1245.56;
	int size = 5;
	float b = 10;

#ifndef	DEBUG
	clnt = clnt_create (host, LOGB_PROG, LOGB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	logb_1_arg.a = vector;
	logb_1_arg.b = b;
	logb_1_arg.size = size;

	result_1 = logb_1(&logb_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		for (int i=0;i<size;i++){
			printf("index %d: %F", i, vector[i]);
		}

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;


	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	logb_prog_1 (host);
exit (0);
}
