/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logb.h"
#include <math.h>
#include <stdio.h>

int *
logb_1_svc(arguments *argp, struct svc_req *rqstp)
{
	static int  result;

	for (int i=0; i<argp->size; i++){
		argp->a[i] = logf(argp->a[i])/logf(argp->b);
		printf("for index %d we have:%F", i, a[i]);
	}
}

	

	return &result;
}
