/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGB_H_RPCGEN
#define _LOGB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	float *a;
	float b;
	int size;
};
typedef struct arguments arguments;

#define LOGB_PROG 0x23451111
#define LOGB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define logb 1
extern  int * logb_1(arguments *, CLIENT *);
extern  int * logb_1_svc(arguments *, struct svc_req *);
extern int logb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define logb 1
extern  int * logb_1();
extern  int * logb_1_svc();
extern int logb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGB_H_RPCGEN */
