/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logb.h"

bool_t
xdr_arguments (XDR *xdrs, arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->a, sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
